export default {
  CHANGE_LOGIN_STATUS: "CHANGE_LOGIN_STATUS",
  SET_USER_INFO: "SET_USER_INFO",
  SET_USER_LIST: "SET_USER_LIST",
  UPDATE_AVATAR_HSAH: "UPDATE_AVATAR_HASH",
  UPDATE_USER_FOLLOWS: "UPDATE_USER_FOLLOWS"
};
